Улучшение скрипта обновления, добавление скрипта апгрейда, добавлены изменённые иконки рабочего стола

diff --git a/scripts/system-upgrade b/scripts/system-upgrade
--- a/scripts/system-upgrade
+++ b/scripts/system-upgrade
@@ -2,25 +2,25 @@
 
 terminal="exo-open --launch TerminalEmulator"
 
-notify_title="Обнавление системы"
-notify_body="Все обновления системы были завершены успешно."
+notify_title="Апгрейд системы"
+notify_body="Все обновления системы для апгрейда были загружены."
 notify_body_error="Обнаружено несколько ошибок - "
+notify_body_version_error="Не указана версия системы, до которой необходимо совершить обновление!"
 notify_icon="update-low"
 notify_icon_error="update-high"
 notify_id=$(cat "$(dirname "$0")/notify-ids" | grep -oP "${0##*/} \K([\d]+)")
 
-log_file="/tmp/update-log"
+log_file="/tmp/system-update-log"
 
 log_sfx=" 2>> $log_file ; echo \$? >> $log_file ; "
+ver_plug="__ver__"
 
 commands=()
-commands=("${commands[@]}" "/usr/bin/dnf upgrade --refresh -y $log_sfx")
-commands=("${commands[@]}" "dnf autoremove -y | dnf clean all $log_sfx")
-commands=("${commands[@]}" "/usr/bin/flatpak update -y $log_sfx")
-commands=("${commands[@]}" "flatpak remove --unused --delete-data -y $log_sfx")
-commands=("${commands[@]}" "/sbin/btrfs balance start -v -dusage=100 / $log_sfx")
+commands=("${commands[@]}" "dnf install dnf-plugin-system-upgrade -y $log_sfx")
+commands=("${commands[@]}" "system-upgrade download --releasever=$ver_plug $log_sfx")
 commands=("${commands[@]}" "$(dirname "$0")/${0##*/} -n $USER ; echo -e '\a' ; ")
 commands=("${commands[@]}" "/usr/bin/read -t 120 -p \"Для выхода нажмите ENTER (в противном случае программа сама завершится через 2 минуты)\" ; ")
+commands=("${commands[@]}" "dnf system-upgrade reboot")
 
 check() {
     [ ! -f $log_file ] && exit 1
@@ -36,6 +36,12 @@ check() {
 
 update() {
     command_line="${commands[@]}"
+    if [[ "$command_line" == *"$ver_plug"* ]]; then
+        sudo -H -u $USER notify-send -u critical -r $notify_id -i "$notify_icon_error" "$notify_title" "$notify_body_version_error"
+        echo "$notify_body_version_error"
+        exit 1
+    fi
+
     rm $log_file 2> /dev/null ; touch $log_file
     pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY PATH=$PATH $terminal /bin/bash -c "$command_line"
     wait
@@ -44,7 +50,7 @@ update() {
 help() {
 echo -e "Скрипт для упрощения применения обновлений системы.\n"
     echo -e "\t-t\t--terminal <name>\tИспользование конкретного эмулятора терминала\n\t\t\t\t\tвместо оного по-умолчанию.\n"
-    echo -e "\t-c\t--command <name>\tДобавление произвольной команды в конец сценария.\n"
+    echo -e "\t-v\t--version <version number>\tНомер версии для апгрейда.\n"
     echo -e "\t-n\t--notify <user>\t\tПроверка успешности обновлений и вывод\n\t\t\t\t\tуведомления о завершении стандартного сценария\n\t\t\t\t\t(вызывается автоматически).\n"
     echo -e "\t-s\t--script\t\tВывод списка команд сценария.\n"
     echo -e "\t-h\t--help\t\t\tВывод данной справки.\n"
@@ -63,8 +69,10 @@ while [[ $# -gt 0 ]] ; do
             terminal="$2"
             shift
             ;;
-        "-c" | "--command")
-            commands=("${commands[@]}" "$2 ; ")
+        "-v" | "--version")
+            for i in ${!commands[@]}; do
+                commands[i]="${commands[i]//$ver_plug/$2}"
+            done
             shift
             ;;
         "-s" | "--script")
